[package]
name = "kalosm-common"
version = "0.3.0"
edition = "2021"
description = "Helpers for kalosm downloads and candle utilities"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
candle-core.workspace = true
hf-hub = { version = "0.3.0", optional = true }
reqwest = { version = "0.11.24", default-features = false }
tokio = { version = "1.36.0", features = ["full"] }
dirs = "5.0.1"
tracing = "0.1.40"
httpdate = "1.0.3"
indicatif = "0.17.8"
metal = { version = "0.29.0", optional = true }

[features]
metal = ["dep:metal"]
default-tls = ["reqwest/default-tls", "dep:hf-hub"]
rustls-tls = ["reqwest/rustls"]
